import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import TopMenu from "./components/topMenu/TopMenu";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "600", "700", "800", "900"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full`}>
      <body className="flex flex-col min-h-screen">
        <TopMenu />
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
